variables:
  GRADLE_OPTS: "-Dorg.gradle.internal.launcher.welcomeMessageEnabled=false"
  CACHE_COMPRESSION_LEVEL: "fastest"
  ARTIFACT_COMPRESSION_LEVEL: "fast"
  FF_USE_FASTZIP: 1
  GRADLE_IMAGE: "${HTL_NEXUS_PROXY}/gradle:8.10.0-jdk21"

before_script:
  - export GRADLE_USER_HOME=$CI_PROJECT_DIR/.gradle


cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - "$CI_PROJECT_DIR/.gradle"
  policy: pull-push

stages:
  - deploy

deploy:
  image: "$GRADLE_IMAGE"
  stage: deploy
  tags:
    - saas-linux-medium-amd64
  script:
    - gradle publish
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: ($CI_COMMIT_BRANCH == 'main' ||  $CI_COMMIT_BRANCH == 'master') && $CI_COMMIT_TAG
    - if: '$CI_MERGE_REQUEST_LABELS =~ /pipeline:jdk21/'
      variables:
        GRADLE_IMAGE: "${HTL_NEXUS_PROXY}/gradle:8.10.0-jdk21"
